Update variable structure and include testinfra
AFCYBER-DREAM/ansible-role-packages pull request #1
Opened 2019-04-26 16:01 UTC by leader716

Included the testing for debian based nodes
Update testinfra to confirm that test packages are installed

2019-05-08 13:11 UTC, ragingpastry requested changes

2019-05-08 13:11 UTC, ragingpastry commented on tasks/redhat.yml
> +    - packages.update_all == True
Lint error here. ansible-lint wants this as "true" instead of "True"

We could also just cast packages.update_all to a bool and then put the check like this:

`packages.update_all | bool` or `packages.update_all` (without the check == True)

Either way we should modify this so that it will pass the lint stage

2019-05-08 13:11 UTC, ragingpastry commented on tasks/debian.yml
> +    update_cache: "{{ packages.debian.update_cache | default('yes') }}"
This will break when run against Debian instances that don't have a defined debian dictionary under packages. I could see this coming up when this role is ran against a diverse inventory that only takes action against certain OS targets. For example, if we have Debian and RHEL hosts in our inventory but we are only installing a RHEL package that is included by default on Debian.

This won't be a problem in Ansible 2.8 because they will start including support for defining default values for nested dicts (https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.8.html#jinja-undefined-values), however until then we will have to use a different syntax.

2019-05-09 18:51 UTC, leader716 commented on tasks/redhat.yml
> +    - packages.update_all == True
I have corrected this in the last commit

2019-05-09 18:52 UTC, leader716 commented on tasks/debian.yml
> +    update_cache: "{{ packages.debian.update_cache | default('yes') }}"
Updated the when logic to handle the missing variables. I also updated the testing to test these kinds of scenarios.

2019-05-10 15:43 UTC, merged